#pragma once

#        define HOLD_ON_OTHER_KEY_PRESS

#        undef LOCKING_SUPPORT_ENABLE
#        undef LOCKING_RESYNC_ENABLE
#        define LAYER_STATE_8BIT

#        undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#        undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#        undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#        undef ENABLE_RGB_MATRIX_BREATHING
#        undef ENABLE_RGB_MATRIX_BAND_SAT
#        undef ENABLE_RGB_MATRIX_BAND_VAL
#        undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#        undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#        undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#        undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#        undef ENABLE_RGB_MATRIX_CYCLE_ALL
#        undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#        undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#        undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#        undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#        undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#        undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#        undef ENABLE_RGB_MATRIX_DUAL_BEACON
#        undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#        undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// #     undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#        define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT // Sets the default mode, if none has been set